name: postcalib

channels:
    - astropy

dependencies:
    - astropy
    - astroquery
    - Cython
    - cycler
    - matplotlib
    - numpy
    - scipy
    - ruffus
    - shutilwhich
    - pyregion
    - lmfit
